version: '3'

services:

  app:
    build: ./dockerfiles/app/
    volumes:
      - ./:/var/www/
      - /$HOME/.composer/cache/:/$HOME/.composer/cache/
    expose:
      - 9000
      - 9001
    environment:
      - USERID=$UID
      - USER=$USER

  nginx:
    build: ./dockerfiles/nginx/
    volumes:
      - ./:/var/www
    expose:
      - 80
    ports:
      - 80:80

  mysql:
    image: mysql:5.7.23
    volumes:
      - db-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: a_database
       MYSQL_USER: a_database
       MYSQL_PASSWORD: a_database

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
    db-data:
      external: false